[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
  
  [headers.values]
    X-Frame-Options = "ALLOW"
 #   X-XSS-Protection = "1; mode=block"
  #  Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-value headers are expressed with multi-line strings.

[[redirects]]
  from = "https://www.facebook.com/fn.coders"
  to = "https://www.facebook.com/fn.coders"
  status = 301
  force = true
  query = {path = ":path"} #  apply this rule for /old-path?path=example
  conditions = {Language = ["en","es"], Country = ["US"]}
